/*
 * HexaEditorDialog.java
 *
 * Created on 27. leden 2008, 17:35
 */
package dtxmanager.hexa;

/**
 *
 */
public class HexaEditorDialog extends javax.swing.JDialog {

    private int[] data;
    private int ofsetBase;
    private int dataBase;

    /**
     * Creates new form HexaEditorDialog
     */
    public HexaEditorDialog() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgData = new javax.swing.ButtonGroup();
        btgCaptions = new javax.swing.ButtonGroup();
        jtbRowHeaderTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaHexView = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        mniCaptionsHexa = new javax.swing.JRadioButtonMenuItem();
        mniCaptionsDeca = new javax.swing.JRadioButtonMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        mniDataHexa = new javax.swing.JRadioButtonMenuItem();
        mniDataDeca = new javax.swing.JRadioButtonMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        mniClose = new javax.swing.JMenuItem();

        jtbRowHeaderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));

        setTitle("Hexadecimal");
        setModal(true);

        jtaHexView.setEditable(false);
        jtaHexView.setColumns(80);
        jtaHexView.setRows(20);
        jScrollPane1.setViewportView(jtaHexView);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        mnuView.setMnemonic('V');
        mnuView.setText("View");

        btgCaptions.add(mniCaptionsHexa);
        mniCaptionsHexa.setSelected(true);
        mniCaptionsHexa.setText("Hexadecimal captions");
        mniCaptionsHexa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onHexCaptions(evt);
            }
        });
        mnuView.add(mniCaptionsHexa);

        btgCaptions.add(mniCaptionsDeca);
        mniCaptionsDeca.setText("Decimal captions");
        mniCaptionsDeca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onDecCaptions(evt);
            }
        });
        mnuView.add(mniCaptionsDeca);
        mnuView.add(jSeparator1);

        btgData.add(mniDataHexa);
        mniDataHexa.setSelected(true);
        mniDataHexa.setText("Hexadecimal data");
        mniDataHexa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onHexData(evt);
            }
        });
        mnuView.add(mniDataHexa);

        btgData.add(mniDataDeca);
        mniDataDeca.setText("Decimal data");
        mniDataDeca.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                onDecData(evt);
            }
        });
        mnuView.add(mniDataDeca);
        mnuView.add(jSeparator2);

        mniClose.setText("Close view");
        mniClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniCloseActionPerformed(evt);
            }
        });
        mnuView.add(mniClose);

        jMenuBar1.add(mnuView);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_mniCloseActionPerformed

    private void onHexCaptions(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onHexCaptions
        if (evt.getStateChange() == evt.SELECTED) {
            setOfsetBase(16);
        }
    }//GEN-LAST:event_onHexCaptions

    private void onDecCaptions(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onDecCaptions
        if (evt.getStateChange() == evt.SELECTED) {
            setOfsetBase(10);
        }
    }//GEN-LAST:event_onDecCaptions

    private void onHexData(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onHexData
        if (evt.getStateChange() == evt.SELECTED) {
            setDataBase(16);
        }
    }//GEN-LAST:event_onHexData

    private void onDecData(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_onDecData
        if (evt.getStateChange() == evt.SELECTED) {
            setDataBase(10);
        }
    }//GEN-LAST:event_onDecData

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HexaEditorDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgCaptions;
    private javax.swing.ButtonGroup btgData;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jtaHexView;
    private javax.swing.JTable jtbRowHeaderTable;
    private javax.swing.JRadioButtonMenuItem mniCaptionsDeca;
    private javax.swing.JRadioButtonMenuItem mniCaptionsHexa;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JRadioButtonMenuItem mniDataDeca;
    private javax.swing.JRadioButtonMenuItem mniDataHexa;
    private javax.swing.JMenu mnuView;
    // End of variables declaration//GEN-END:variables

    public void showWithData(int[] data) {
        setData(data);
        refreshData();
        super.setVisible(true);
    }

    private void setData(int[] data) {
        this.data = data;
    }

    private void setOfsetBase(int i) {
        this.ofsetBase = i;
        refreshData();
    }

    private void setDataBase(int i) {
        this.dataBase = i;
        refreshData();
    }

    private void refreshData() {

        int numbersPerRow = 32;
        if (ofsetBase == 10) {
            numbersPerRow = 20;
        }

        int dataPos = 0;
        int linePos = 0;

        StringBuilder sb = new StringBuilder();
        StringBuilder txtBuilder = new StringBuilder();

        while (dataPos < data.length) {

            /*Possible line info*/
            if (linePos == 0) {
                if (ofsetBase == 10) {
                    sb.append(String.format("%05d| ", dataPos));
                }
                else {
                    sb.append(String.format("%05X| ", dataPos));
                }
                txtBuilder.delete(0, txtBuilder.length());
            }

            /*The numbers*/
            if (dataBase == 10) {
                sb.append(String.format("%03d ", data[dataPos]));
            }
            else {
                sb.append(String.format("%02X ", data[dataPos]));
            }

            if (data[dataPos] > 32 && data[dataPos] < 128) {
                txtBuilder.appendCodePoint(data[dataPos]);
            }
            else {
                txtBuilder.append(".");
            }

            linePos++;
            dataPos++;

            if (linePos == numbersPerRow || dataPos == data.length) {
                sb.append(" | ").append(txtBuilder);
                sb.append(System.getProperty("line.separator"));
                linePos = 0;
            }

        }

        jtaHexView.setText(sb.toString());
    }

}
