/*
 * DocumentationFrame.java
 *
 * Created on 27. leden 2008, 11:24
 */
package dtxmanager;

import java.io.BufferedReader;
import java.io.InputStream;
import java.io.InputStreamReader;

/**
 *
 */
public class DocumentationFrame extends javax.swing.JFrame {

    /**
     * Creates new form DocumentationFrame
     */
    public DocumentationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnClose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaManual = new javax.swing.JTextArea();

        setTitle("Documentation");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jtaManual.setColumns(81);
        jtaManual.setEditable(false);
        jtaManual.setFont(new java.awt.Font("Monospaced", 0, 12));
        jtaManual.setRows(32);
        jScrollPane1.setViewportView(jtaManual);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DocumentationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaManual;
    // End of variables declaration//GEN-END:variables

    void showWithLanguage(int l) {
        try {
            StringBuffer sb = new StringBuffer();
            String sp = System.getProperty("line.separator");
            String fn;
            if (l == 0) {
                fn = "/dtxmanager/docs/readme.txt";
            }
            else {
                fn = "/dtxmanager/docs/readme_cs.txt";
            }
            String txt = "";
            InputStream is = txt.getClass().getResourceAsStream(fn);
            InputStreamReader isr = new InputStreamReader(is, "utf-8");
            BufferedReader br = new BufferedReader(isr);
            while ((fn = br.readLine()) != null) {
                sb.append(fn);
                sb.append(sp);
            }
            br.close();
            jtaManual.setText(sb.toString());
        }
        catch (Exception e) {
            jtaManual.setText("Not available");
            e.printStackTrace();
        }
        jtaManual.setCaretPosition(0);
        setVisible(true);
    }
}
